import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/lib/theme";

export const metadata = {
	title: "Intelligent Eats",
	description: "Generated by create next app"
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<ThemeProvider theme={theme}>{children}</ThemeProvider>
			</body>
		</html>
	);
}
