import { create } from "zustand";
import { persist } from "zustand/middleware";

/**
 * Zustand store for managing user data.
 * @type {Object}
 * @property {string[]} userFavouriteMeals - Array of user's favorite meals.
 * @property {string[]} userGeneratedMeals - Array of meals generated by the user.
 * @property {string[]} userIngredients - Array of user's ingredients.
 * @property {string[]} userDislikedIngredients - Array of user's disliked ingredients.
 * @property {Object|null} userParameters - Object containing user's parameters.
 * @property {string|null} userEmail - Email of the user.
 * @property {string|null} userName - Name of the user.
 * @property {string|null} authorisedUser - Authorized user.
 * @property {string} prompt - Prompt for generating a meal.
 * @property {string} mealToRemix - Name of the meal to remix.
 * @property {string} lastMeal - Last generated meal.
 * @property {string} lastRecipe - Last generated recipe.
 * @property {string[]} lastIngredientQuantities - Last generated ingredient quantities.
 * @property {string[]} lastIngredientsNeeded - Last generated needed ingredients.
 * @property {string[]} lastIngredientsUser - Last generated user ingredients.
 * @property {string} lastMealImage - Last generated meal image.
 * @property {Function} setUserFavouriteMeals - Function to set user's favorite meals.
 * @property {Function} setUserGeneratedMeals - Function to set user's generated meals.
 * @property {Function} setUserIngredients - Function to set user's ingredients.
 * @property {Function} setUserDislikedIngredients - Function to set user's disliked ingredients.
 * @property {Function} setUserParameters - Function to set user's parameters.
 * @property {Function} setUserEmail - Function to set user's email.
 * @property {Function} setUserName - Function to set user's name.
 * @property {Function} setPrompt - Function to set prompt for generating a meal.
 * @property {Function} setMealToRemix - Function to set meal to remix.
 * @property {Function} setAuthorisedUser - Function to set authorised user.
 * @property {Function} setLastMeal - Function to set last generated meal.
 * @property {Function} setLastRecipe - Function to set last generated recipe.
 * @property {Function} setLastIngredientQuantities - Function to set last generated ingredient quantities.
 * @property {Function} setLastIngredientsNeeded - Function to set last generated needed ingredients.
 * @property {Function} setLastIngredientsUser - Function to set last generated user ingredients.
 * @property {Function} setLastMealImage - Function to set last generated meal image.
 */
const useDataStore = create(
	persist(
		(set) => ({
			userFavouriteMeals: [],
			userGeneratedMeals: [],
			userIngredients: [],
			userDislikedIngredients: [],
			userParameters: null,
			userEmail: null,
			userName: null,
			authorisedUser: null,
			prompt: "",
			mealToRemix: "",
			lastMeal: "",
			lastRecipe: "",
			lastIngredientQuantities: [],
			lastIngredientsNeeded: [],
			lastIngredientsUser: [],
			lastMealImage: "",
			setUserFavouriteMeals: (meals) => set({ userFavouriteMeals: meals }),
			setUserGeneratedMeals: (meals) => set({ userGeneratedMeals: meals }),
			setUserIngredients: (ingredients) => set({ userIngredients: ingredients }),
			setUserDislikedIngredients: (ingredients) => set({ userDislikedIngredients: ingredients }),
			setUserParameters: (parameters) => {
				set({ userParameters: parameters });
			},
			setUserEmail: (email) => set({ userEmail: email }),
			setUserName: (name) => set({ userName: name }),
			setPrompt: (prompt) => set({ prompt }),
			setMealToRemix: (mealToRemix) => set({ mealToRemix }),
			setAuthorisedUser: (authorisedUser) => set({ authorisedUser }),
			setLastMeal: (lastMeal) => set({ lastMeal }),
			setLastRecipe: (lastRecipe) => set({ lastRecipe }),
			setLastIngredientQuantities: (lastIngredientQuantities) => set({ lastIngredientQuantities }),
			setLastIngredientsNeeded: (lastIngredientsNeeded) => set({ lastIngredientsNeeded }),
			setLastIngredientsUser: (lastIngredientsUser) => set({ lastIngredientsUser }),
			setLastMealImage: (image) => set({ lastMealImage: image })
		}),
		{
			name: "data-store3"
		}
	)
);

export default useDataStore;
